# Generated by Django 2.1.5 on 2020-07-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post'},
        ),
    ]
